Image customCss Implementation
cmpsr/composer pull request #186
Opened 2020-10-29 14:22 UTC by dawinValenzuela

## Please delete checklist items and sections that are not relevant

**Checklist**

- [x] New feature (non-breaking change which adds functionality)

**Please check if the PR fulfills these requirements**

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Storybook or docs have been added / updated (for bug fixes / features)

**Other information**:
Add customCss implementation

2020-10-29 14:25 UTC, guilean requested changes

2020-10-29 14:25 UTC, guilean commented on packages/styled-components/src/components/primitives/Image/Image.styled.ts
> +  ${(props) => customCss(props)}
Looks identical except the tag. Maybe we can create a single StyledImage which will render an img tag as default and we can provide as="source" for the source tag.

2020-10-29 14:52 UTC, guilean approved these changes

2020-10-29 16:01 UTC, tkanzakic requested changes

2020-10-30 07:52 UTC, tkanzakic requested changes

2020-10-30 07:52 UTC, tkanzakic commented on packages/styled-components/src/components/primitives/Image/Image.stories.tsx
> +    customCss={select('Custom css', customCss, customCss.none)}
use a plain text as in other components

2020-10-30 10:44 UTC, tkanzakic requested changes

2020-10-30 10:44 UTC, tkanzakic commented on packages/styled-components/src/components/primitives/Image/Image.styled.ts
> +  ${(props) => customCss(props)}
this approach is no longer valid, check this PR https://github.com/cmpsr/composer/pull/187

2020-10-30 10:44 UTC, tkanzakic commented on packages/styled-components/src/components/primitives/Image/Image.tsx
> +        className={cn(imageClassName, { custom: customCss })}
not necessary with the new approach

2020-10-30 10:44 UTC, tkanzakic commented on packages/styled-components/src/components/primitives/Image/Image.tsx
> +        className={cn(imageClassName, { custom: customCss })}
not necessary with the new approach

2020-10-30 12:47 UTC, tkanzakic approved these changes

2020-10-30 12:47 UTC, merged