[COM-297] Modal component
cmpsr/composer pull request #357
Opened 2022-02-01 03:19 UTC by dawinValenzuela

## Please delete checklist items and sections that are not relevant

**Checklist**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Please check if the PR fulfills these requirements**

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Storybook or docs have been added / updated (for bug fixes / features)

**What is the ticket / issue associated with this change?** (Link to the ticket or issue)
https://impulsumvc.atlassian.net/browse/COM-297

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

**Storybook Link** (Link to a local storybook url to review new functionality)
http://localhost:8080/?path=/story/components-primitives-modal--all

2022-02-01 10:28 UTC, tkanzakic requested changes
storybook is not building because of a type error

2022-02-01 14:02 UTC, tkanzakic requested changes
Some errors found while testing

<img width="1709" alt="Screenshot 2022-02-01 at 14 59 04" src="https://user-images.githubusercontent.com/884028/151982257-0c2bbff1-5de3-43fc-a112-a9e0a5f397b9.png">
<img width="1705" alt="Screenshot 2022-02-01 at 14 59 47" src="https://user-images.githubusercontent.com/884028/151982263-e6729c26-8953-45c0-a7b7-305f25ea9064.png">

2022-02-01 14:02 UTC, tkanzakic commented on packages/components/src/components/primitives/Modal/Modal.tsx
> +Modal.CloseButton = ModalCloseButton;
I tend to remember we talked about not doing this but accepting props

2022-02-01 14:02 UTC, tkanzakic commented on packages/components/src/components/primitives/Modal/Modal.stories.tsx
> +  size: ModalSizes[0],
please add more config options

2022-02-17 05:43 UTC, TheEnmanuel23 reviewed
**UNOFFICIAL REVIEW:**
After clicking on 20rem and right aligned button:
![image](https://user-images.githubusercontent.com/11969862/154412655-d1785609-07da-4167-b6e7-25eb259ef860.png)
It seems to have left alignment instead of right alignment

2022-02-21 11:01 UTC, guilean approved these changes

2022-02-21 11:41 UTC, tkanzakic approved these changes

2022-02-21 12:16 UTC, merged