COM-372: implement inline alert component
cmpsr/composer pull request #412
Opened 2022-03-11 19:58 UTC by TheEnmanuel23

## Please delete checklist items and sections that are not relevant

**Checklist**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Please check if the PR fulfills these requirements**

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Storybook or docs have been added / updated (for bug fixes / features)

**What is the ticket / issue associated with this change?** (Link to the ticket or issue)
https://impulsumvc.atlassian.net/browse/COM-372

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

**Storybook Link** (Link to a local storybook url to review new functionality)

2022-03-11 20:00 UTC, TheEnmanuel23 reviewed
I reused Alert props and status array since they are basically  the same

2022-03-11 20:05 UTC, TheEnmanuel23 commented on packages/components/src/theme/ComposerTheme/Components/InlineAlert.ts
> +        ...rest.theme.components.Alert.baseStyle(rest).icon.status[status],
I wanted to use somethig like this. as an object:
`...Alert.baseStyle.icon.status[status]`
I din't get anything, due to Alert theme is defined as function in its `baseStyles` property, so I changed it `...Alert.baseStyle(props).icon.status[status]`
but I was getting another error from typescript.

2022-03-22 11:56 UTC, tkanzakic requested changes

2022-03-22 11:56 UTC, tkanzakic commented on packages/components/src/components/notifications/InlineAlert/InlineAlert.tsx
> +    </Flex>
this should use composition

2022-05-04 15:51 UTC, tkanzakic commented on packages/components/src/components/notifications/InlineAlert/InlineAlert.tsx
> +import { createContext } from '@chakra-ui/react-utils';
yes, it returns the provider and a hook to consume the context in the same call

2022-05-04 16:14 UTC, guilean approved these changes

2022-05-05 07:03 UTC, tkanzakic approved these changes

2022-05-05 07:03 UTC, merged