COM-477 Getting Started + Storybook improvements + IDEA folder
cmpsr/composer pull request #417
Opened 2022-03-17 16:49 UTC by gvillo

**What is the ticket / issue associated with this change?** (Link to the ticket or issue)

- Adds useful addons for storybook
- Improves gitignore file
- Adds IDEA folder
- Add script to run the app at root level
- Improves READMEs with getting started  
- Migrated turbo config to `turbo.json`

2022-03-22 13:24 UTC, tkanzakic submitted a review, later dismissed
You have to update the Dockerfile too to use the new commando to build the storybook

2022-04-04 13:14 UTC, gvillo commented
> You have to update the Dockerfile too to use the new commando to build the storybook

thank you, fixed it!

2023-01-24 03:21 UTC, gvillo commented on projects/ui-storybook/.storybook/main.ts
> +    '@storybook/addon-a11y',
really good addon to add Accessibility tab to storybook

2023-01-24 03:21 UTC, gvillo commented on package.json
> -  "turbo": {
this way of adding turbo was deprecated, so I moved to a turbo.json file

2023-01-27 07:35 UTC, tkanzakic requested changes

2023-01-27 07:35 UTC, tkanzakic commented on packages/components/src/components/dataDisplay/NumberedList/NumberedList.tsx
> +            return cloneElement(child, { number, paddingTop: '0.75rem' } as NumberedListProps);
Is this typecast necessary?, also there is an extra indentation that does not follow the rest of the repo

2023-01-27 07:35 UTC, tkanzakic commented on packages/components/README.md
> +## Running the app
This is no longer valid, the storyboook is launched from the root of the rep

2023-01-27 07:35 UTC, tkanzakic commented on packages/blocks/src/AccordionGallery/components/AccordionGalleryAccordion.tsx
> +            return cloneElement(child, { index } as AccordionProps);
Is this typecast necessary?

2023-01-27 07:35 UTC, tkanzakic commented on README.md
> +You can do it from the root of this folder by running `yarn run components:storybook`, please be asure to run `yarn install` first on packages.
This is no longer true, the storybook is launched from the root of the repo

2023-01-27 07:35 UTC, tkanzakic commented on README.md
> +You can find all the implementations `packages` folder. Every package has his own readme.
```suggestion
You can find all the implementations in the `packages` folder. Every package has his own readme.
```

2023-01-27 07:35 UTC, tkanzakic commented on README.md
> +This is a monorepo that supports components, analytics, 3rd party integrations (such as contentful), payment methods, messaging and much more.
We do not support payment methods 😉

2023-01-27 07:35 UTC, tkanzakic commented on README.md
> +This is a monorepo that supports components, analytics, 3rd party integrations (such as contentful), payment methods, messaging and much more.
And we have a better definition of composer _somewhere_, I will search for it and share it with you

2023-01-27 07:35 UTC, tkanzakic commented on README.md
> +Add the following package under `packages` folder and be sure you add the README file, scripts on root package.json, so everyone can understand how to use it correctly. Don't forget to push vscode an
We should reword this statement

2023-02-07 20:54 UTC, closed without merging